### ISSUE TITLE
Satismeter dialog disappears

### ISSUE THREAD

**Issue by borjaruiz** [satismeter/satismeter-android#4]
Hi,

I'm trying your sdk, and I have a problem while displaying any dialog at the same time that satismeter nps is shown.

In that moment, your nps dialog disappears before the user being able to click any score.

Tested in android 9 and 10.

**Comment by jsedlacek** [comment]
@borjaruiz Thanks for reporting. Let me check if can we fix that.

**Comment by marsalmonico** [comment]
Also when I click outside the nps dialog, it disappears. So is too easy to accidentaly close it before the user clicks any score.
Tested in Android 7 and 8. Could be possible to add a parameter to manage if cancel the activity/dialog when touching outside?

**Comment by borjaruiz** [comment]
Hi, still waiting a solution... No library updates since may 2019...

**Comment by jsedlacek** [comment]
@borjaruiz thanks for checking. We are going to investigate more next week, and get back to you.

**Comment by jsedlacek** [comment]
We have added a gray overlay that indicates that the survey can be closed by clicking outside of it.

Available in version 1.3.0.

@marsalmonico @borjaruiz Does this work for you? Please comment/reopen if you still observe incorrect behavior.

**Comment by borjaruiz** [comment]
The gray overlay is ok, but we need to be able to configure if we want the dialog to be cancelled when clicking outside. (like native dialogs, setCancelable). This way the user will be forced to select an option.

**Comment by jsedlacek** [comment]
@borjaruiz let me check with the team what can we do about making the dialog not cancellable by clicking away from the dialog.

**Comment by jsedlacek** [comment]
@borjaruiz Fixed in version 1.4.0
