### ISSUE TITLE
Dialog language is always english

### ISSUE THREAD

**Issue by borjaruiz** [satismeter/satismeter-android#6]
Hi, although user device language is spanish or italian, the satismeter dialog is always displayed in english.

**Comment by jsedlacek** [comment]
@borjaruiz Thanks for reporting. We will check with this happens, and get back.

**Comment by Gflexy** [comment]
Hi, @jsedlacek , Can you please tell me, what kind of Language representation expecting the backend server? Is it enough to pass only the lang tag like ("en", "es", "pl" etc.) or it should be lang + country representation (ru_RU, en_IN, fr_FR) or maybe something else?

**Comment by jsedlacek** [comment]
@Gflexy it's lang + country, the same way browsers send the header.

**Comment by jsedlacek** [comment]
@borjaruiz Fixed in version 1.4.0
