### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [satismeter/satismeter-android#8]
I would like to disable `jetifier` in a near future since it will bring considerable build speed improvements in my project, but I found that the Satismeter SDK is one of the last libraries I am using, that still uses the old `Android Support Libraries`.

The steps to change to AndroidX are pretty straight forward
https://developer.android.com/jetpack/androidx/migrate

Satismeter Android SDK: `1.5.0`

**Comment by jsedlacek** [comment]
@florianPOLARSTEPS Thanks - let me check what can we do here, and get back.

**Comment by man4ik** [comment]
@florianPOLARSTEPS thanks for raising the issue. Could you please try 1.5.1

Please pay attention the lib has been migrated to `mavenCentral`
`implementation 'com.satismeter:satismeter:1.5.1'`

**Comment by florianPOLARSTEPS** [comment]
`1.5.1` Looks good! 
Tested with https://github.com/plnice/can-i-drop-jetifier

**Comment by jsedlacek** [comment]
@florianPOLARSTEPS Thanks!
