### ISSUE TITLE
Changelog is missing 1.5.1

### ISSUE THREAD

**Issue by borjaruiz** [satismeter/satismeter-android#9]
Hi, I think it's a typing error. In changelog you just missed 1.5.1, and I think 1.5.2 does not exist yet. Isn't it?

**Comment by jsedlacek** [comment]
@borjaruiz The 1.5.2 version can be found here:
https://search.maven.org/artifact/com.satismeter/satismeter/1.5.2/aar

We have switched the hosting provider of our SDK since jCenter has been deprecated.

**Comment by borjaruiz** [comment]
Thanks, I didn't realise that
